// <auto-generated />
namespace Casando.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Tabela_De_Usuario_E_Perfil : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tabela_De_Usuario_E_Perfil));
        
        string IMigrationMetadata.Id
        {
            get { return "201410282146004_Tabela_De_Usuario_E_Perfil"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
