// <auto-generated />
namespace Casando.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class N_Para_N_Convidado_E_Presente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(N_Para_N_Convidado_E_Presente));
        
        string IMigrationMetadata.Id
        {
            get { return "201411161709350_N_Para_N_Convidado_E_Presente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
