// <auto-generated />
namespace Casando.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Adicionando_Campo_ComConvite_Tabela_Convidado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adicionando_Campo_ComConvite_Tabela_Convidado));
        
        string IMigrationMetadata.Id
        {
            get { return "201411081058075_Adicionando_Campo_ComConvite_Tabela_Convidado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
