// <auto-generated />
namespace Casando.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Alterando_Nome_Da_Coluna_NumeroConvites : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alterando_Nome_Da_Coluna_NumeroConvites));
        
        string IMigrationMetadata.Id
        {
            get { return "201411081048002_Alterando_Nome_Da_Coluna_NumeroConvites"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
